
const About = () => {
    return (
        <div>
            <h2 style={{fontSize:'4rem', textAlign:'center'}}>This is the About Us page </h2>
            <p style={{textAlign:'center'}}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem laborum, repudiandae fugiat enim distinctio harum? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem quod, doloremque aut, impedit explicabo magni odio nemo neque provident asperiores deserunt! Repellat rerum labore itaque nesciunt vero soluta libero placeat, nobis quod velit delectus, pariatur repudiandae alias iste asperiores nisi laborum suscipit. Ullam, nam porro, fugiat eligendi est provident atque voluptatibus libero adipisci nesciunt iusto facere, illum sed! Obcaecati optio repellendus quo pariatur velit odio fugiat rem odit error dignissimos, aspernatur adipisci molestias voluptatem! Amet inventore impedit rerum, hic ratione sed! Obcaecati provident adipisci voluptatem hic, eaque nesciunt a fugit saepe labore deserunt enim tenetur est quaerat libero sunt alias dicta fuga, ex id facere tempore temporibus ipsa maxime nemo. Provident, blanditiis. Distinctio inventore omnis consectetur laboriosam vero vitae pariatur obcaecati recusandae, delectus hic sequi molestiae voluptatum provident ex ab reiciendis earum totam deserunt et quas illo consequatur. Quasi velit porro, maxime adipisci nostrum pariatur voluptas? Quasi, totam quis error inventore ut sequi magnam repellat sint quidem labore expedita dolorem nam laboriosam nisi tempora amet maiores quia at maxime quaerat necessitatibus provident magni soluta doloribus. Corrupti architecto odit consequatur. Dolore doloribus sapiente expedita ducimus amet blanditiis? Perspiciatis vel dolorem a! Provident cumque voluptatibus consectetur consequatur rem itaque voluptatem ipsum. Sed, aut inventore, quo excepturi voluptates odio quos vel perspiciatis soluta eligendi maiores natus voluptas distinctio quas, laboriosam itaque iusto ullam dolore explicabo minus beatae sapiente omnis! Quam eveniet adipisci accusantium dolorem culpa a sunt saepe sequi. Quasi, vero repellendus vitae unde fugit repellat ex enim facere doloremque excepturi nesciunt perspiciatis at praesentium quos consequatur dolores atque mollitia reiciendis, sequi reprehenderit corrupti hic. Corrupti, dolorum ipsum. Veniam maxime optio laborum, cum voluptatum alias cumque quas porro. Inventore veritatis hic ullam? Debitis officiis fugiat iste, eligendi voluptate et eaque laudantium iure, voluptatibus iusto adipisci animi asperiores expedita accusantium ut! Quae, laborum neque.</p>
        </div>
    );
};

export default About;